auth_mechanisms = plain login

passdb {
  driver = static
  args = user=${MAIL_USER}@${MAIL_DOMAIN} password={SHA512-CRYPT}$6$REPLACE_WITH_HASH
}

userdb {
  driver = static
  args = uid=5000 gid=5000 home=/var/mail/${MAIL_DOMAIN}/${MAIL_USER}
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}
