mail_location = maildir:/var/mail/%d/%n
mail_privileged_group = mail
mail_uid = 5000
mail_gid = 5000
autoexpunge = 0
mailbox Drafts {
  auto = no
}
mailbox Junk {
  auto = no
  special_use =
}
mailbox Spam {
  auto = no
  special_use =
}
mailbox Trash {
  auto = no
}
